### ISSUE TITLE
Xdebug Support with Paranoia activated

### ISSUE THREAD

**Issue by devkinetic** [drupal-composer/drupal-paranoia#15] opened 2019-04-19 15:27 UTC
### Issue links
https://stackoverflow.com/questions/14629975/xdebug-in-netbeans-not-stopping-on-breakpoint-inside-file-in-web-roots-paren/16092457

### Expected behavior
When setting a breakpoint with a given IDE (PHPStorm in this case) one is able to debug. 

### Actual behavior
The breakpoint is not detected, and complains about path mappings. 

### Steps to reproduce
1. Run project with an xdebug enabled version of PHP (7.2 in this case)
2. Require paranoia & configure
3. Set a breakpoint in IDE
4. Run code, no breakpoint detected.

I spent a couple hours trying every possible combination of path mappings with no success. Removed paranoia and everything immediately worked. I thought about having the ability to "disable" paranoia for development purposes, but I'm not sure how one would do this aside from removing it from the project which is undesirable.

**Comment by brambaud** [comment] 2019-04-21 18:10
Hi!

I personally use drupal-paranoia, xdebug and PHPStorm everyday without any issues.

Could you provide more information about your setup please ? Are you using docker, PHPStorm configuration, xdebug configuration etc..

> The breakpoint is not detected, and complains about path mappings.

Did you add the mappings for the `app-dir` and the `web-dir`?

**Comment by devkinetic** [comment] 2019-04-25 18:13
Oddly enough, much like in that issue I linked to above, the issue has resolved itself...?

I took your advice and required paranoia again.

1. Enabled xdebug in PHP
2. Started my local docker instance.
3. Configured PHPStorm with a debug configuration, using a single mapping for the root of my project, as one would normally do. 
4. Set a breakpoint within a contrib module under /app/modules/contrib/x/x.module 

I am running drupal-composer, drupal-paranoia, docker4drupal. While I don't have a direct resolution, my gut is telling me that something was either hung in a cache somewhere or I'm a bit loony.

> Did you add the mappings for the app-dir and the web-dir?

I tried as many different mapping configs as I could conjure.
- root
- root, web
- root, app
- root, web, app
- web
- app
- web, app

**Comment by jkribeiro** [comment] 2019-06-24 13:38
@devkinetic It seems to be some problem on your end with your local setup. If you point your local web server to use the `/app` folder as docroot you will have the 'standard' Drupal structure, no difference between a normal installation. I would try it. 

I'm also personally using paranoia and Xdebug, other developers from my company are using both as well. 

I'm closing this issue as "cannot reproduce" since it's been open for two months and no one else has complained about it.

Thanks.

**Closed as completed by jkribeiro** 2019-06-24 13:38 UTC
Labels: cannot reproduce

**Comment by devkinetic** [comment] 2019-06-24 16:24
Forgot to round back on this. I got it working no problems. I don't have an
answer as to why. Came back a few days later and it's fine. I can backup
that I've now since done this to many other sites without issue.
